apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketeer-frontend
  namespace: ticketeer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketeer-frontend
  template:
    metadata:
      labels:
        app: ticketeer-frontend
    spec:
      containers:
        - name: frontend
          image: ticketeer-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ticketeer-frontend-config
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
