apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketeer-ingress
  namespace: ticketeer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ticketeer.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ticketeer-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticketeer-frontend
                port:
                  number: 3000
